import test from 'node:test';
import assert from 'node:assert/strict';
import { buildResearchCaseTimeline, RESEARCH_TIMELINE_VERSION } from '../server/researchTimelineService.js';

const caseId='research:2026-09-10:lighter:market_share_gain';
const detail={case:{id:caseId,headline:'Volume Share Gain',family:'market_share_gain',score:73,severity:'medium',primarySignal:{id:'signal:lighter:share',type:'market_share_gain'}},protocol:{id:2,slug:'lighter',name:'Lighter'},snapshot:{date:'2026-09-10'}};
const obs=(snapshotDate,state='PRESENT',extra={})=>({snapshotDate,state,score:state==='PRESENT'?73:null,severity:state==='PRESENT'?'medium':null,evidence:[],comparison:null,cacheId:`obs-${snapshotDate}`,createdAt:`${snapshotDate}T12:05:00Z`,...extra});
const history=(observations,family='market_share_gain')=>({series:{key:`lighter:${family}`,signalFamily:family},engineVersion:'v3',evaluationMode:'RETROSPECTIVE',anchorDate:observations.at(-1)?.snapshotDate,observations});
const build=(observations,extra={})=>buildResearchCaseTimeline({detail,caseRow:{snapshot_date:'2026-09-10',created_at:'2026-09-10T13:00:00Z'},latestCanonical:observations.at(-1)?.snapshotDate||'2026-09-10',history:history(observations,extra.family),...extra});

test('case without follow-up returns one deterministic CASE_CREATED event',()=>{const result=build([obs('2026-09-10')]);assert.equal(result.events.length,1);assert.equal(result.events[0].id,`timeline:case:${caseId}`);assert.equal(result.timelineVersion,RESEARCH_TIMELINE_VERSION)});
test('reappearance is one semantic event rather than signal, lifecycle and watch duplicates',()=>{const watch={id:44,canonical_date:'2026-09-11',created_at:'2026-09-11T12:10:00Z',metadata_json:{canonicalDate:'2026-09-11',lifecycleState:'NEW',update:{type:'REAPPEARED',changed:true,significance:'HIGH',explanation:'Again'}}};const result=build([obs('2026-09-09'),obs('2026-09-10','ABSENT'),obs('2026-09-11')],{watchEvaluations:[watch]});const items=result.events.filter((item)=>item.eventType==='SIGNAL_REAPPEARED');assert.equal(items.length,1);assert.ok(items[0].references.some((item)=>item.type==='watch_evaluation'));assert.equal(result.summary.mergedEvents,1)});
test('present to absent resolves while not-evaluable never resolves',()=>{const resolved=build([obs('2026-09-10'),obs('2026-09-11'),obs('2026-09-12','ABSENT')]);assert.ok(resolved.events.some((item)=>item.eventType==='LIFECYCLE_RESOLVED'));const gap=build([obs('2026-09-10'),obs('2026-09-11','NOT_EVALUABLE',{notEvaluableReason:'MISSING_OI'})]);assert.ok(gap.events.some((item)=>item.eventType==='DATA_GAP'));assert.ok(!gap.events.some((item)=>item.eventType==='LIFECYCLE_RESOLVED'))});
test('restoration after a data gap is not called reappearance',()=>{const result=build([obs('2026-09-10','NOT_EVALUABLE'),obs('2026-09-11')]);assert.ok(result.events.some((item)=>item.eventType==='DATA_RESTORED'));assert.ok(!result.events.some((item)=>item.eventType==='SIGNAL_REAPPEARED'))});
test('daily PRESENT noise is compressed to lifecycle transitions',()=>{const observations=Array.from({length:10},(_,index)=>obs(`2026-09-${String(10+index).padStart(2,'0')}`));const result=build(observations);assert.ok(result.events.length<observations.length);assert.equal(result.events.filter((item)=>item.eventType==='LIFECYCLE_PERSISTING').length,1)});
test('strengthening and weakening use the existing lifecycle derivation over prefixes',()=>{const turn=(date,value)=>obs(date,'PRESENT',{evidence:[{label:'Volume / OI',value}],comparison:{value:1}});const observations=[turn('2026-09-10',5),turn('2026-09-11',6),turn('2026-09-12',7),turn('2026-09-13',6),turn('2026-09-14',5)];const result=buildResearchCaseTimeline({detail:{...detail,case:{...detail.case,family:'turnover_structure'}},caseRow:{snapshot_date:'2026-09-10',created_at:'2026-09-10T13:00:00Z'},latestCanonical:'2026-09-14',history:history(observations,'turnover_structure')});assert.ok(result.events.some((item)=>item.eventType==='LIFECYCLE_STRENGTHENING'));assert.ok(result.events.some((item)=>item.eventType==='LIFECYCLE_WEAKENING'))});
test('watch no-change rows are suppressed while baseline and material change remain',()=>{const rows=[{id:1,canonical_date:'2026-09-11',created_at:'2026-09-11T13:00:00Z',metadata_json:{update:{type:'FIRST_CHECK',changed:false}}},{id:2,canonical_date:'2026-09-12',created_at:'2026-09-12T13:00:00Z',metadata_json:{update:{type:'NO_MEANINGFUL_CHANGE',changed:false}}},{id:3,canonical_date:'2026-09-13',created_at:'2026-09-13T13:00:00Z',metadata_json:{lifecycleState:'STRENGTHENING',update:{type:'STRENGTH_INCREASED',changed:true,significance:'MEDIUM',explanation:'Material increase.'}}}];const result=build([obs('2026-09-10'),obs('2026-09-11'),obs('2026-09-12'),obs('2026-09-13')],{watchEvaluations:rows});assert.equal(result.events.filter((item)=>item.eventType==='WATCH_BASELINE_ESTABLISHED').length,1);assert.equal(result.events.filter((item)=>item.eventType==='WATCH_CHANGE_DETECTED').length,1);assert.ok(result.summary.suppressedDuplicateOrNoiseEvents>=1)});
test('engine methodology changes become baseline resets rather than market changes',()=>{const row={id:8,canonical_date:'2026-09-11',created_at:'2026-09-11T13:00:00Z',metadata_json:{update:{type:'ENGINE_VERSION_CHANGED',changed:false,significance:'NONE',explanation:'Version changed'}}};const result=build([obs('2026-09-10'),obs('2026-09-11')],{watchEvaluations:[row]});assert.equal(result.events.filter((item)=>item.eventType==='METHODOLOGY_BASELINE_RESET').length,1)});
test('external runs and synthesis revisions are summarized without one event per finding',()=>{const externalRuns=[{id:3,status:'COMPLETED',provider:'tavily',research_version:'v3',window_start:'2026-09-03',window_end:'2026-09-10',window_key:'7d',created_at:'2026-09-11T09:00:00Z',completed_at:'2026-09-11T09:01:00Z',summary_json:{totalFindings:3,officialSources:1},findings_json:[{id:1,title:'One'},{id:2,title:'Two'},{id:3,title:'Three'}]},{id:4,status:'FAILED',provider:'tavily',created_at:'2026-09-12T09:00:00Z',completed_at:'2026-09-12T09:01:00Z',findings_json:[]}];const syntheses=[{id:5,synthesis_version:'v1',created_at:'2026-09-11T10:00:00Z',synthesis_payload:{confirmedFacts:[{}],externalFacts:[{}],hypotheses:[],unknowns:[{}]}},{id:6,synthesis_version:'v1',created_at:'2026-09-13T10:00:00Z',synthesis_payload:{confirmedFacts:[{}],externalFacts:[],hypotheses:[{}],unknowns:[]}}];const result=build([obs('2026-09-10'),obs('2026-09-13')],{externalRuns,syntheses});assert.equal(result.summary.researchEvents,2);assert.equal(result.summary.synthesisEvents,2);assert.equal(result.events.filter((item)=>item.eventType==='SYNTHESIS_CREATED').length,1);assert.equal(result.events.filter((item)=>item.eventType==='SYNTHESIS_REFRESHED').length,1)});
test('event IDs and same-day ordering are stable and malformed source rows do not break valid events',()=>{const extra={externalRuns:[{id:9,status:'COMPLETED',provider:'x',created_at:'invalid',findings_json:[]},{id:10,status:'COMPLETED',provider:'x',created_at:'2026-09-11T14:00:00Z',summary_json:{totalFindings:0},findings_json:[]}],syntheses:[{id:11,synthesis_version:'v1',created_at:'2026-09-11T15:00:00Z',synthesis_payload:{}}]};const one=build([obs('2026-09-10'),obs('2026-09-11')],extra);const two=build([obs('2026-09-10'),obs('2026-09-11')],extra);assert.deepEqual(one.events.map((item)=>item.id),two.events.map((item)=>item.id));assert.equal(one.events[0].eventType,'CASE_CREATED');assert.ok(one.events.some((item)=>item.id==='timeline:external:10'))});
