import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { deriveWatchUpdate, watchlistPriority } from '../server/researchWatchlistService.js';

const evaluation = (overrides = {}) => ({ signalState:'PRESENT', lifecycleState:'PERSISTING', lifecycleConfidence:'HIGH', score:70, strengthValue:5, strengthMetric:'volume_oi_vs_peer_median', reappeared:false, engineVersion:'v3', lifecycleVersion:'v1', canonicalDate:'2026-09-11', ...overrides });

test('first watch establishes a baseline without a false update',()=>assert.equal(deriveWatchUpdate(null,evaluation()).type,'FIRST_CHECK'));
test('small strength noise is suppressed consistently with lifecycle materiality',()=>assert.deepEqual(deriveWatchUpdate(evaluation(),evaluation({strengthValue:5.05,canonicalDate:'2026-09-12'})).changed,false));
test('material strength changes are classified in both directions',()=>{assert.equal(deriveWatchUpdate(evaluation(),evaluation({strengthValue:6})).type,'STRENGTH_INCREASED');assert.equal(deriveWatchUpdate(evaluation(),evaluation({strengthValue:4})).type,'STRENGTH_DECREASED')});
test('lifecycle transitions are meaningful',()=>assert.equal(deriveWatchUpdate(evaluation(),evaluation({lifecycleState:'STRENGTHENING'})).type,'LIFECYCLE_CHANGED'));
test('resolved has high-priority semantics',()=>{const update=deriveWatchUpdate(evaluation(),evaluation({signalState:'ABSENT',lifecycleState:'RESOLVED'}));assert.equal(update.type,'RESOLVED');assert.equal(update.significance,'HIGH')});
test('reappeared has high-priority semantics',()=>assert.equal(deriveWatchUpdate(evaluation({signalState:'ABSENT',lifecycleState:'RESOLVED'}),evaluation({lifecycleState:'NEW',reappeared:true})).type,'REAPPEARED'));
test('not-evaluable and restored data remain distinct',()=>{assert.equal(deriveWatchUpdate(evaluation(),evaluation({signalState:'NOT_EVALUABLE',lifecycleState:null})).type,'BECAME_NOT_EVALUABLE');assert.equal(deriveWatchUpdate(evaluation({signalState:'NOT_EVALUABLE',lifecycleState:null}),evaluation()).type,'DATA_RESTORED')});
test('engine and lifecycle version changes reset the baseline',()=>{assert.equal(deriveWatchUpdate(evaluation(),evaluation({engineVersion:'v4'})).type,'ENGINE_VERSION_CHANGED');assert.equal(deriveWatchUpdate(evaluation(),evaluation({lifecycleVersion:'v2'})).changed,false)});
test('absolute share-strength threshold uses percentage points',()=>{const prior=evaluation({strengthMetric:'share_change_pp',strengthValue:2});assert.equal(deriveWatchUpdate(prior,evaluation({strengthMetric:'share_change_pp',strengthValue:2.4})).changed,false);assert.equal(deriveWatchUpdate(prior,evaluation({strengthMetric:'share_change_pp',strengthValue:2.5})).type,'STRENGTH_INCREASED')});
test('watch persistence is append-only and idempotent by case, canonical day, and versions', async()=>{const migration=await readFile(new URL('../migrations/008_research_watchlist.sql',import.meta.url),'utf8');assert.match(migration,/UNIQUE\(case_id, canonical_date, engine_version, lifecycle_version\)/);assert.doesNotMatch(migration,/ON DELETE CASCADE|DELETE FROM research_watch_evaluations/i)});
test('meaningful updates sort above new, strengthening, persisting and unavailable cases',()=>{const changed={update:{changed:true,significance:'MEDIUM'},currentState:{lifecycleState:'PERSISTING'}};const fresh={update:{changed:false},currentState:{lifecycleState:'NEW'}};const stable={update:{changed:false},currentState:{lifecycleState:'PERSISTING'}};const unavailable={update:{changed:false},currentState:{signalState:'NOT_EVALUABLE'}};assert.ok(watchlistPriority(changed)>watchlistPriority(fresh));assert.ok(watchlistPriority(fresh)>watchlistPriority(stable));assert.ok(watchlistPriority(stable)>watchlistPriority(unavailable))});
