import { getSql } from './db.js';
import { snapshotDateKey } from './analyticsMath.js';
import { getPersistedResearchCase, validResearchCaseId } from './researchCasePersistence.js';
import { getSignalHistory } from './signalHistoryService.js';
import { deriveSignalLifecycle, LIFECYCLE_CONFIG } from './signalLifecycleService.js';

export const RESEARCH_TIMELINE_VERSION = 'v1';
const EVENT_PRIORITY = { SIGNAL_REAPPEARED:1,LIFECYCLE_RESOLVED:2,LIFECYCLE_STRENGTHENING:3,LIFECYCLE_WEAKENING:4,LIFECYCLE_NEW:5,DATA_GAP:6,DATA_RESTORED:7,LIFECYCLE_PERSISTING:8,WATCH_CHANGE_DETECTED:9,METHODOLOGY_BASELINE_RESET:10,EXTERNAL_RESEARCH_FAILED:11,EXTERNAL_RESEARCH_PARTIAL:12,EXTERNAL_RESEARCH_COMPLETED:13,NEW_EXTERNAL_EVIDENCE:14,SYNTHESIS_CREATED:15,SYNTHESIS_REFRESHED:16,WATCH_BASELINE_ESTABLISHED:17,CASE_CREATED:0 };

function utcDate(value) { return snapshotDateKey(value); }
function timestamp(value) { if (!value) return null; const date = value instanceof Date ? value : new Date(value); return Number.isNaN(date.getTime()) ? null : date.toISOString(); }
function shift(date, days) { const value = new Date(`${date}T00:00:00Z`); value.setUTCDate(value.getUTCDate()+days); return value.toISOString().slice(0,10); }
function ref(type,id) { return id == null ? null : { type, id:String(id) }; }
function event({id,caseId,eventType,category,effectiveDate,occurredAt,title,summary,significance='INFO',source,data={},references=[]}) { return { id,caseId,eventType,category,effectiveDate:utcDate(effectiveDate),occurredAt:timestamp(occurredAt),title,summary,significance,source,data,references:references.filter(Boolean) }; }
function stateTitle(value) { return String(value || '').replaceAll('_',' ').toLowerCase().replace(/^./,(letter)=>letter.toUpperCase()); }

function lifecyclePrefixes(history) {
  return history.observations.map((observation,index) => ({ observation, lifecycle:deriveSignalLifecycle({ ...history, anchorDate:observation.snapshotDate, observations:history.observations.slice(0,index+1), summary:null }) }));
}

function lifecycleEvents(caseId, caseDate, history) {
  const prefixes = lifecyclePrefixes(history); const events=[]; let suppressed=0;
  for (let index=1; index<prefixes.length; index+=1) {
    const previous=prefixes[index-1]; const current=prefixes[index]; const date=current.observation.snapshotDate;
    if (date<=caseDate) continue;
    const reference=ref('signal_observation',current.observation.cacheId || `${history.series.key}:${date}`);
    let item=null;
    if (previous.observation.state==='NOT_EVALUABLE'&&current.observation.state!=='NOT_EVALUABLE') item=event({id:`timeline:signal:${reference.id}:data-restored`,caseId,eventType:'DATA_RESTORED',category:'DATA',effectiveDate:date,occurredAt:current.observation.createdAt,title:'Data restored',summary:'Required data became available again for this Signal evaluation.',significance:'MEDIUM',source:'signal_observations',data:{previousState:previous.observation.state,currentState:current.observation.state,lifecycle:current.lifecycle},references:[reference]});
    else if (current.observation.state==='NOT_EVALUABLE'&&previous.observation.state!=='NOT_EVALUABLE') item=event({id:`timeline:signal:${reference.id}:data-gap`,caseId,eventType:'DATA_GAP',category:'DATA',effectiveDate:date,occurredAt:current.observation.createdAt,title:'Signal evaluation unavailable',summary:'The semantic Signal could not be evaluated on this canonical snapshot.',significance:'MEDIUM',source:'signal_observations',data:{reason:current.observation.notEvaluableReason,previousState:previous.observation.state,currentState:current.observation.state},references:[reference]});
    else if (current.lifecycle.flags.reappeared) item=event({id:`timeline:signal:${reference.id}:reappeared`,caseId,eventType:'SIGNAL_REAPPEARED',category:'SIGNAL',effectiveDate:date,occurredAt:current.observation.createdAt,title:'Signal reappeared',summary:'The pattern qualified again after an evaluable absence.',significance:'HIGH',source:'signal_observations+lifecycle',data:{previousLifecycle:previous.lifecycle.lifecycleState,currentLifecycle:current.lifecycle.lifecycleState,score:current.observation.score,reappeared:true,lifecycle:current.lifecycle},references:[reference]});
    else if (current.lifecycle.lifecycleState!==previous.lifecycle.lifecycleState) {
      const next=current.lifecycle.lifecycleState;
      const types={NEW:'LIFECYCLE_NEW',PERSISTING:'LIFECYCLE_PERSISTING',STRENGTHENING:'LIFECYCLE_STRENGTHENING',WEAKENING:'LIFECYCLE_WEAKENING',RESOLVED:'LIFECYCLE_RESOLVED'};
      const summaries={NEW:'The pattern qualified on the latest evaluable snapshot.',PERSISTING:`The pattern remained present across ${current.lifecycle.stats.consecutivePresentEvaluable} consecutive evaluable observations.`,STRENGTHENING:'The pattern remained present and its measured strength increased materially.',WEAKENING:'The pattern remained present, but its measured strength declined materially.',RESOLVED:'The pattern no longer qualified on the latest evaluable snapshot.'};
      if (types[next]) item=event({id:`timeline:signal:${reference.id}:${types[next].toLowerCase()}`,caseId,eventType:types[next],category:'LIFECYCLE',effectiveDate:date,occurredAt:current.observation.createdAt,title:next==='RESOLVED'?'Signal resolved':`Lifecycle ${stateTitle(next)}`,summary:summaries[next],significance:['RESOLVED'].includes(next)?'HIGH':['STRENGTHENING','WEAKENING'].includes(next)?'MEDIUM':'LOW',source:'signal_lifecycle',data:{previousLifecycle:previous.lifecycle.lifecycleState,currentLifecycle:next,score:current.observation.score,lifecycle:current.lifecycle},references:[reference]});
    }
    if(item) events.push(item); else suppressed+=1;
  }
  return {events,prefixes,suppressed};
}

function externalEvents(caseId,runs,syntheses){const events=[];const sorted=[...runs].sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at)));const latestSynthesis=[...syntheses].sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).at(-1);for(const run of sorted){if(!['COMPLETED','PARTIAL','FAILED'].includes(run.status))continue;const occurred=run.completed_at||run.created_at;const summary=run.summary_json||{};const findings=Array.isArray(run.findings_json)?run.findings_json:[];const stale=latestSynthesis&&Date.parse(occurred)>Date.parse(latestSynthesis.created_at);const type=run.status==='FAILED'?'EXTERNAL_RESEARCH_FAILED':run.status==='PARTIAL'?'EXTERNAL_RESEARCH_PARTIAL':stale?'NEW_EXTERNAL_EVIDENCE':'EXTERNAL_RESEARCH_COMPLETED';const findingCount=Number(summary.totalFindings??findings.length);const officialCount=Number(summary.officialSources??0);events.push(event({id:`timeline:external:${run.id}`,caseId,eventType:type,category:'RESEARCH',effectiveDate:utcDate(occurred),occurredAt:occurred,title:type==='NEW_EXTERNAL_EVIDENCE'?'New external evidence available':run.status==='FAILED'?'External Research failed':run.status==='PARTIAL'?'External Research partially completed':'External Research completed',summary:run.status==='FAILED'?'The persisted research run did not complete successfully.':`${findingCount} relevant ${findingCount===1?'finding':'findings'} · ${officialCount} official ${officialCount===1?'source':'sources'}.`,significance:run.status==='FAILED'?'MEDIUM':'INFO',source:run.provider||'external_research',data:{status:run.status,provider:run.provider,researchVersion:run.research_version,researchWindow:{from:utcDate(run.window_start),to:utcDate(run.window_end),key:run.window_key},summary,topFindings:findings.slice(0,3),synthesisStale:Boolean(stale)},references:[ref('external_research_run',run.id),...findings.slice(0,3).map((finding)=>ref('external_research_finding',finding.id))]}));}return events;}

function synthesisEvents(caseId,rows){return [...rows].sort((a,b)=>String(a.created_at).localeCompare(String(b.created_at))).map((row,index)=>{const payload=row.synthesis_payload||{};const facts=payload.confirmedFacts||[];const external=payload.externalFacts||[];const hypotheses=payload.hypotheses||[];const unknowns=payload.unknowns||[];return event({id:`timeline:synthesis:${row.id}`,caseId,eventType:index?'SYNTHESIS_REFRESHED':'SYNTHESIS_CREATED',category:'SYNTHESIS',effectiveDate:utcDate(row.created_at),occurredAt:row.created_at,title:index?'Research Synthesis refreshed':'Research Synthesis created',summary:`${facts.length} confirmed facts · ${external.length} external facts · ${hypotheses.length} hypotheses · ${unknowns.length} unknowns.`,significance:'INFO',source:'research_case_syntheses',data:{synthesisVersion:row.synthesis_version,conclusionConfidence:payload.conclusion?.confidence||null,confirmedFacts:facts.length,externalFacts:external.length,hypotheses:hypotheses.length,unknowns:unknowns.length},references:[ref('synthesis',row.id),ref('external_research_run',row.external_research_run_id)]});});}

function watchSemanticType(update,current){if(update?.type==='REAPPEARED')return'SIGNAL_REAPPEARED';if(update?.type==='RESOLVED')return'LIFECYCLE_RESOLVED';if(update?.type==='BECAME_NOT_EVALUABLE')return'DATA_GAP';if(update?.type==='DATA_RESTORED')return'DATA_RESTORED';if(update?.type==='ENGINE_VERSION_CHANGED')return'METHODOLOGY_BASELINE_RESET';if(update?.type==='LIFECYCLE_CHANGED'){const types={NEW:'LIFECYCLE_NEW',PERSISTING:'LIFECYCLE_PERSISTING',STRENGTHENING:'LIFECYCLE_STRENGTHENING',WEAKENING:'LIFECYCLE_WEAKENING',RESOLVED:'LIFECYCLE_RESOLVED'};return types[current?.lifecycleState]||'WATCH_CHANGE_DETECTED';}return'WATCH_CHANGE_DETECTED';}
function mergeWatchEvents(caseId,base,rows){const events=[...base];let merged=0,suppressed=0;for(const row of rows){const data=row.metadata_json||{};const update=data.update||{};if(['NO_MEANINGFUL_CHANGE'].includes(update.type)){suppressed+=1;continue;}let item;if(update.type==='FIRST_CHECK')item=event({id:`timeline:watch:${row.id}:baseline`,caseId,eventType:'WATCH_BASELINE_ESTABLISHED',category:'WATCH',effectiveDate:row.canonical_date,occurredAt:row.created_at,title:'Watch baseline established',summary:'Zig recorded the first canonical follow-up evaluation for this watched Case.',significance:'INFO',source:'research_watch_evaluations',data,references:[ref('watch_evaluation',row.id)]});else{const type=watchSemanticType(update,data);item=event({id:`timeline:watch:${row.id}:${type.toLowerCase()}`,caseId,eventType:type,category:type.startsWith('LIFECYCLE')?'LIFECYCLE':type.startsWith('DATA')?'DATA':type.startsWith('SIGNAL')?'SIGNAL':'WATCH',effectiveDate:row.canonical_date,occurredAt:row.created_at,title:type==='METHODOLOGY_BASELINE_RESET'?'Monitoring methodology baseline reset':type==='SIGNAL_REAPPEARED'?'Signal reappeared':type==='LIFECYCLE_RESOLVED'?'Signal resolved':'Watch change detected',summary:update.explanation||'A meaningful watched-state change was detected.',significance:update.significance||'MEDIUM',source:'research_watch_evaluations',data,references:[ref('watch_evaluation',row.id)]});}
    const duplicate=events.find((candidate)=>candidate.effectiveDate===item.effectiveDate&&candidate.eventType===item.eventType);if(duplicate){duplicate.references=[...duplicate.references,...item.references];duplicate.data={...duplicate.data,watchEvaluation:item.data};merged+=1;}else events.push(item);
  }return{events,merged,suppressed};}

export function buildResearchCaseTimeline({detail,caseRow,latestCanonical,history,externalRuns=[],syntheses=[],watchEvaluations=[],currentStatus=null,dbQueries=0,durationMs=0}){
  const caseId=detail.case.id;const caseDate=utcDate(caseRow.snapshot_date||detail.snapshot.date);const created=event({id:`timeline:case:${caseId}`,caseId,eventType:'CASE_CREATED',category:'CASE',effectiveDate:caseDate,occurredAt:caseRow.created_at,title:'Research Case created',summary:`${detail.protocol.name} — ${detail.case.headline}. Zig recorded Signal score ${detail.case.score} (${detail.case.severity}).`,significance:'INFO',source:'research_cases',data:{protocol:detail.protocol,headline:detail.case.headline,score:detail.case.score,severity:detail.case.severity,primarySignal:detail.case.primarySignal},references:[ref('research_case',caseId),ref('signal',detail.case.primarySignal?.id)]});
  const lifecycle=history?lifecycleEvents(caseId,caseDate,history):{events:[],prefixes:[],suppressed:0};const watched=mergeWatchEvents(caseId,[created,...lifecycle.events],watchEvaluations);let events=[...watched.events,...externalEvents(caseId,externalRuns,syntheses),...synthesisEvents(caseId,syntheses)];events=events.filter((item)=>item.effectiveDate&&item.effectiveDate>=caseDate);events.sort((a,b)=>a.effectiveDate.localeCompare(b.effectiveDate)||(EVENT_PRIORITY[a.eventType]??99)-(EVENT_PRIORITY[b.eventType]??99)||String(a.occurredAt||'').localeCompare(String(b.occurredAt||''))||a.id.localeCompare(b.id));
  const latestPrefix=lifecycle.prefixes.at(-1);const meaningful=events.filter((item)=>!['CASE_CREATED','LIFECYCLE_PERSISTING','WATCH_BASELINE_ESTABLISHED','EXTERNAL_RESEARCH_COMPLETED','EXTERNAL_RESEARCH_PARTIAL','SYNTHESIS_CREATED','SYNTHESIS_REFRESHED','METHODOLOGY_BASELINE_RESET'].includes(item.eventType)).length;const categoryCount=(category)=>events.filter((item)=>item.category===category).length;
  return{timelineVersion:RESEARCH_TIMELINE_VERSION,case:{id:caseId,protocol:detail.protocol,headline:detail.case.headline,snapshotDate:caseDate,status:currentStatus},series:history?.series||{key:`${detail.protocol.slug}:${detail.case.family}`,signalFamily:detail.case.family},range:{from:caseDate,to:latestCanonical},currentFollowUp:{canonicalDate:latestCanonical,signalState:latestPrefix?.observation.state||null,notEvaluableReason:latestPrefix?.observation.notEvaluableReason||null,lifecycleState:latestPrefix?.lifecycle.lifecycleState||null,lifecycleConfidence:latestPrefix?.lifecycle.confidence||null},disclosure:history?`Historical Signal states are retrospectively evaluated using Signal Engine ${history.engineVersion} and Lifecycle ${LIFECYCLE_CONFIG.version}.`:'Historical Signal follow-up is temporarily unavailable; persisted research events remain visible.',summary:{events:events.length,meaningfulChanges:meaningful,signalEvents:categoryCount('SIGNAL'),lifecycleEvents:categoryCount('LIFECYCLE'),researchEvents:categoryCount('RESEARCH'),synthesisEvents:categoryCount('SYNTHESIS'),watchEvents:events.filter((item)=>item.references.some((reference)=>reference.type==='watch_evaluation')).length,statusEvents:0,mergedEvents:watched.merged,suppressedDuplicateOrNoiseEvents:lifecycle.suppressed+watched.suppressed,externalResearchRuns:externalRuns.length,synthesisRevisions:syntheses.length},versions:{signalEngine:history?.engineVersion||null,lifecycle:LIFECYCLE_CONFIG.version,timeline:RESEARCH_TIMELINE_VERSION},events,performance:{dbQueries,durationMs}};
}

async function optionalQuery(sql,query,params,section,failures){try{return await sql.query(query,params)}catch(error){failures.push({section,error:'SOURCE_UNAVAILABLE'});console.error('Research Timeline source unavailable',{section,error:error.message});return[]}}

export async function getResearchCaseTimeline({caseId},sql=getSql()){
  if(!validResearchCaseId(caseId))throw new Error('Invalid research case id');const started=Date.now();
  const detail=await getPersistedResearchCase(caseId,sql);if(!detail)throw new Error('Research Timeline requires a persisted Research Case');
  const failures=[];const [caseRows,latestRows,externalRuns,syntheses,watchEvaluations]=await Promise.all([
    sql.query('SELECT id,snapshot_date::text AS snapshot_date,created_at FROM research_cases WHERE id=$1 LIMIT 1',[caseId]),
    sql.query('SELECT MAX(snapshot_date)::text AS date FROM protocol_daily_snapshots'),
    optionalQuery(sql,`SELECT r.*,COALESCE((SELECT jsonb_agg(jsonb_build_object('id',f.id,'title',f.title,'confidence',f.confidence,'sourceType',f.source_type,'eventDate',f.event_date::text) ORDER BY f.relevance_score DESC,f.id) FROM external_research_findings f WHERE f.research_run_id=r.id),'[]'::jsonb) AS findings_json FROM external_research_runs r WHERE r.case_id=$1 ORDER BY r.created_at`,[caseId],'external_research',failures),
    optionalQuery(sql,'SELECT id,synthesis_version,external_research_run_id,synthesis_payload,created_at FROM research_case_syntheses WHERE case_id=$1 ORDER BY created_at,id',[caseId],'synthesis',failures),
    optionalQuery(sql,'SELECT id,canonical_date::text AS canonical_date,metadata_json,created_at FROM research_watch_evaluations WHERE case_id=$1 ORDER BY canonical_date,id',[caseId],'watch',failures),
  ]);
  const caseRow=caseRows[0];const latestCanonical=utcDate(latestRows[0]?.date)||detail.snapshot.date;const historyStart=shift(detail.snapshot.date,-(LIFECYCLE_CONFIG.highConfidenceObservations+22));let history=null;try{history=await getSignalHistory({caseId,period:'90d',anchorDate:latestCanonical,startDate:historyStart},sql)}catch(error){failures.push({section:'signal_history',error:'SOURCE_UNAVAILABLE'});console.error('Research Timeline source unavailable',{section:'signal_history',error:error.message})}
  const result=buildResearchCaseTimeline({detail,caseRow,latestCanonical,history,externalRuns,syntheses,watchEvaluations,currentStatus:detail.case.status,dbQueries:9,durationMs:Date.now()-started});return{...result,sourceFailures:failures};
}
