import { useMemo, useState } from 'react';
import { formatUSD } from '../lib/format';
import { getLogoUrl } from '../lib/projectLogos';
import { setResearchCaseStatus, useResearchCaseData } from '../hooks/useResearchFeedData';
import AnalyticsCredit from './AnalyticsCredit';
import ExternalResearchSection from './ExternalResearchSection';

const ACTIONS = [['IGNORED', 'Ignore'], ['WATCHING', 'Watch'], ['RESEARCHING', 'Research']];
const HISTORY_METRICS = [['volume', 'Volume'], ['openInterest', 'Open Interest'], ['tvl', 'TVL'], ['volumeShare', 'Volume Share'], ['volumeOiRatio', 'Volume / OI']];

function date(value) { return value ? new Intl.DateTimeFormat('en-US', { timeZone: 'UTC', month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(`${String(value).slice(0, 10)}T00:00:00.000Z`)) : '—'; }
function compact(value, type = 'usd') { if (value == null || !Number.isFinite(value)) return '—'; if (type === 'count') return String(value); if (type === 'share') return `${value.toFixed(1)}%`; if (type === 'pp') return `${value > 0 ? '+' : ''}${value.toFixed(1)}pp`; if (type === 'ratio') return `${value.toFixed(2)}x`; return formatUSD(value); }
function percentile(value) { return value == null ? '—' : `${Math.round(value * 100)}th`; }

function StatusActions({ item, onSave, saving }) { return <div className="research-status-actions protocol-status-actions">{ACTIONS.map(([value, label]) => <button type="button" key={value} className={item.status === value ? 'is-active' : ''} disabled={saving} onClick={() => onSave(item.status === value ? null : value)}>{label}</button>)}</div>; }

function MetricCard({ label, metric, type = 'usd' }) { return <div className="protocol-metric-card"><span>{label}</span><strong>{compact(metric?.value, type)}</strong>{metric?.source && <small title={`Source: ${metric.source}`}>Source available</small>}</div>; }

function PeerCard({ label, context, type = 'usd' }) { return <div className="protocol-peer-card"><strong>{label}</strong><span>{compact(context?.value, type)}</span><div className="protocol-peer-stats"><small>Rank <b>{context?.rank ? `#${context.rank} / ${context.eligible}` : '—'}</b></small><small>Median <b>{compact(context?.median, type)}</b></small><small>Percentile <b>{percentile(context?.percentile)}</b></small></div>{context?.percentile != null && <i><b style={{ width: `${Math.max(3, context.percentile * 100)}%` }} /></i>}</div>; }

function HistoryChart({ detail, period, metric }) {
  const entry = detail.history.periods[period];
  const points = useMemo(() => {
    const raw = metric === 'volumeShare' ? entry?.volumeShareSeries?.map((item) => ({ date: item.date, value: item.share })) : detail.history.series[metric];
    if (!raw || !entry?.startDate || !entry?.endDate) return [];
    return raw.filter((point) => point.date >= entry.startDate && point.date <= entry.endDate && Number.isFinite(point.value));
  }, [detail, entry, metric]);
  if (!entry?.available) return <div className="protocol-history-empty"><strong>{period.toUpperCase()} history is still being collected</strong><span>{entry?.availableDays || 0} / {entry?.requiredDays || 0} canonical daily snapshots</span></div>;
  if (!points.length) return <div className="protocol-history-empty"><strong>No comparable {metric} history is available.</strong></div>;
  const width = 620; const height = 180; const pad = { top: 12, right: 15, bottom: 30, left: 42 }; const plotW = width - pad.left - pad.right; const plotH = height - pad.top - pad.bottom;
  const values = points.map((point) => point.value); const min = Math.min(...values); const max = Math.max(...values); const range = max - min || Math.max(max * .1, 1);
  const x = (index) => pad.left + (points.length === 1 ? plotW / 2 : index / (points.length - 1) * plotW); const y = (value) => pad.top + (1 - (value - min) / range) * plotH;
  const path = points.map((point, index) => `${index ? 'L' : 'M'} ${x(index)} ${y(point.value)}`).join(' ');
  const start = points[0]; const end = points.at(-1); const share = metric === 'volumeShare'; const ratio = metric === 'volumeOiRatio'; const growth = !share && !ratio && start.value > 0 ? (end.value / start.value - 1) * 100 : null;
  return <div className="protocol-history-chart"><div className="protocol-history-comparison"><span>Start <b>{compact(start.value, share ? 'share' : ratio ? 'ratio' : 'usd')}</b></span><span>Current <b>{compact(end.value, share ? 'share' : ratio ? 'ratio' : 'usd')}</b></span><span>{share ? 'Change' : ratio ? 'Range' : 'Change'} <b>{share ? compact(end.value - start.value, 'pp') : ratio ? `${compact(start.value, 'ratio')} → ${compact(end.value, 'ratio')}` : growth == null ? '—' : `${growth > 0 ? '+' : ''}${growth.toFixed(1)}%`}</b></span></div><svg viewBox={`0 0 ${width} ${height}`} role="img" aria-label={`${metric} history`}><line x1={pad.left} x2={width - pad.right} y1={pad.top + plotH} y2={pad.top + plotH} className="protocol-chart-grid" /><path d={path} className="protocol-chart-line" />{points.map((point, index) => <g key={point.date}><circle cx={x(index)} cy={y(point.value)} r="3" className="protocol-chart-dot"><title>{`${date(point.date)}: ${compact(point.value, share ? 'share' : ratio ? 'ratio' : 'usd')}`}</title></circle>{(index === 0 || index === points.length - 1) && <text x={x(index)} y={height - 8} textAnchor={index === 0 ? 'start' : 'end'} className="protocol-chart-axis">{date(point.date)}</text>}</g>)}</svg></div>;
}

export default function ProtocolResearchView({ caseId, onBack }) {
  const { data, loading, error, refetch } = useResearchCaseData(caseId); const [period, setPeriod] = useState('7d'); const [historyMetric, setHistoryMetric] = useState('volume'); const [saving, setSaving] = useState(false); const [saveError, setSaveError] = useState(null);
  if (loading) return <section className="protocol-research-page"><div className="daily-research-loading"><i /><i /><i /></div></section>;
  if (error || !data) return <section className="protocol-research-page"><div className="daily-research-empty"><strong>{error === 'not-found' ? 'Research case not found.' : 'Protocol research is temporarily unavailable.'}</strong><button type="button" onClick={error === 'not-found' ? onBack : refetch}>Back to Daily Research</button></div></section>;
  const { case: caseItem, protocol, metrics, peerContext, history, methodology } = data;
  const save = async (status) => { setSaving(true); setSaveError(null); try { await setResearchCaseStatus(caseItem.id, status); refetch(); } catch { setSaveError('Unable to save research status.'); } finally { setSaving(false); } };
  return <section className="protocol-research-page" aria-label={`Research dossier for ${protocol.name}`}>
    <button type="button" className="protocol-back" onClick={onBack}>← Daily Research</button>
    <header className="protocol-research-header"><div className="protocol-title"><img src={getLogoUrl(protocol.name) || ''} alt="" onError={(event) => { event.currentTarget.style.display = 'none'; }} /><div><span className="analytics-kicker">Protocol research dossier</span><h1>{protocol.name}</h1><p>{caseItem.headline}</p></div></div><div className="protocol-header-meta"><span className={`research-severity ${caseItem.severity}`}>{caseItem.severity}</span><b>Case score {caseItem.score}</b><span>{caseItem.period} · Data through {date(data.snapshot.date)}</span><StatusActions item={caseItem} onSave={save} saving={saving} /></div></header>
    {saveError && <p className="research-update-error">{saveError}</p>}
    <div className={`protocol-research-grid family-${caseItem.family}`}>
      <section className="protocol-section protocol-why"><span className="analytics-module-kicker">Why Zig flagged this</span><h2>{caseItem.headline}</h2><p>{caseItem.summary}</p><div className="protocol-flag-evidence">{caseItem.evidence.map((item) => <span key={item.key}><small>{item.label}</small><b>{item.formatted}</b></span>)}</div>{caseItem.primarySignal.metadata && <div className="protocol-signal-meta"><span>Peer percentile: {percentile(caseItem.primarySignal.metadata.peerPercentile)}</span><span>Eligible peers: {caseItem.primarySignal.metadata.sampleSize || '—'}</span><span>Market-impact percentile: {percentile(caseItem.primarySignal.metadata.impactPercentile)}</span></div>}<details className="protocol-methodology"><summary>How Zig calculated this</summary><span>{methodology.formula}</span>{methodology.peerComparison && <span>Peer comparison: {methodology.peerComparison}</span>}{methodology.outlierPercentile != null && <span>Observed peer percentile: {methodology.outlierPercentile.toFixed(0)}th</span>}</details></section>
      <aside className="protocol-section protocol-snapshot"><span className="analytics-module-kicker">Current market snapshot</span><div className="protocol-metric-grid"><MetricCard label="24h Volume" metric={metrics?.volume24h} /><MetricCard label="Open Interest" metric={metrics?.openInterest} /><MetricCard label="TVL" metric={metrics?.tvl} /><MetricCard label="Markets" metric={metrics?.marketsCount} type="count" /><MetricCard label="Volume Share" metric={metrics?.volumeShare} type="share" /><MetricCard label="OI Share" metric={metrics?.oiShare} type="share" /><MetricCard label="Volume / OI" metric={metrics?.volumeOiRatio} type="ratio" /><MetricCard label="Share Gap" metric={metrics?.shareGapPp} type="pp" /></div></aside>
      <section className="protocol-section protocol-peers"><span className="analytics-module-kicker">How does it compare?</span><p className="protocol-coverage">Tracked coverage · Volume {data.coverage.volumeAvailable}/{data.coverage.total} · OI {data.coverage.oiAvailable}/{data.coverage.total} · TVL {data.coverage.tvlAvailable}/{data.coverage.total}</p><div className="protocol-peer-grid"><PeerCard label="Volume" context={peerContext.volume} /><PeerCard label="Open Interest" context={peerContext.openInterest} /><PeerCard label="TVL" context={peerContext.tvl} /><PeerCard label="Volume / OI" context={peerContext.volumeOiRatio} type="ratio" /><PeerCard label="Volume Share" context={peerContext.volumeShare} type="share" /><PeerCard label="OI Share" context={peerContext.oiShare} type="share" /></div>{metrics?.shareGapPp?.value != null && <p className="protocol-structure">{metrics.shareGapPp.value >= 0 ? `${protocol.name} represents a larger share of tracked trading activity than of tracked Open Interest.` : `${protocol.name} represents a larger share of tracked Open Interest than of trading activity.`}</p>}</section>
      <section className="protocol-section protocol-history"><span className="analytics-module-kicker">What changed?</span><div className="protocol-history-controls"><div>{['7d', '30d', '90d'].map((value) => <button type="button" key={value} className={period === value ? 'is-active' : ''} onClick={() => setPeriod(value)}>{value.toUpperCase()}</button>)}</div><div>{HISTORY_METRICS.map(([value, label]) => <button type="button" key={value} className={historyMetric === value ? 'is-active' : ''} onClick={() => setHistoryMetric(value)}>{label}</button>)}</div></div><HistoryChart detail={data} period={period} metric={historyMetric} /><p className="protocol-history-progress">Protocol metric coverage: Volume {history.periods[period].protocolMetricDays.volume}/{history.periods[period].requiredDays} · OI {history.periods[period].protocolMetricDays.openInterest}/{history.periods[period].requiredDays} · TVL {history.periods[period].protocolMetricDays.tvl}/{history.periods[period].requiredDays}</p></section>
      <section className="protocol-section protocol-related"><span className="analytics-module-kicker">Related observations</span>{data.relatedSignals.length ? data.relatedSignals.map((item) => <details key={item.id}><summary>{item.title} · score {item.score}</summary><span>{item.evidence?.map((evidence) => `${evidence.label}: ${evidence.formatted}`).join(' · ') || item.summary}</span></details>) : <p>No related observations for this case.</p>}{data.otherSignals.length > 0 && <><h3>Other active signals</h3>{data.otherSignals.map((item) => <p key={item.id}><b>{item.headline}</b> · {item.score}/100</p>)}</>}</section>
      <section className="protocol-section protocol-questions"><span className="analytics-module-kicker">Questions to investigate</span><div><strong>Zig can check</strong>{caseItem.questions.zigCanCheck.map((item) => <span key={item}>{item}</span>)}</div><div><strong>External research</strong>{caseItem.questions.externalResearch.map((item) => <span key={item}>{item}</span>)}</div></section>
      <ExternalResearchSection caseItem={caseItem} initialResearch={data.externalResearch} />
    </div><AnalyticsCredit />
  </section>;
}
