import { useEffect, useMemo, useState } from 'react';
import { Activity, BookOpen, Eye, FileText } from 'lucide-react';
import { getResearchCaseTimeline } from '../hooks/useResearchFeedData';

const FILTERS=['ALL','SIGNAL','RESEARCH','WATCH'];
const CATEGORY_GROUP={SIGNAL:'SIGNAL',LIFECYCLE:'SIGNAL',DATA:'SIGNAL',RESEARCH:'RESEARCH',SYNTHESIS:'RESEARCH',WATCH:'WATCH',CASE:'ALL',STATUS:'WATCH'};
const ICONS={CASE:BookOpen,SIGNAL:Activity,LIFECYCLE:Activity,DATA:Activity,RESEARCH:FileText,SYNTHESIS:FileText,WATCH:Eye,STATUS:Eye};
function day(value){return value?new Intl.DateTimeFormat('en-US',{timeZone:'UTC',month:'short',day:'numeric',year:'numeric'}).format(new Date(`${value}T00:00:00Z`)):'—';}
function time(value){return value?new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(new Date(value)):'—';}
function label(value){return String(value||'').replaceAll('_',' ');}

function TimelineEvent({item}){const Icon=ICONS[item.category]||Activity;return <article className={`research-timeline-event category-${item.category.toLowerCase()} significance-${item.significance.toLowerCase()}`} id={item.id}>
  <i className="timeline-node" aria-hidden="true"><Icon size={13}/></i><div className="timeline-event-body"><div className="timeline-event-head"><span>{item.category}</span><b>{label(item.eventType)}</b>{item.occurredAt&&['RESEARCH','SYNTHESIS'].includes(item.category)&&<time dateTime={item.occurredAt}>{time(item.occurredAt)}</time>}</div><h3>{item.title}</h3><p>{item.summary}</p>{(item.references.length>0||Object.keys(item.data||{}).length>0)&&<details><summary>Event details</summary><div className="timeline-details">{item.data?.previousLifecycle!==undefined&&<span>Previous lifecycle <b>{item.data.previousLifecycle||'Unavailable'}</b></span>}{item.data?.currentLifecycle!==undefined&&<span>Current lifecycle <b>{item.data.currentLifecycle||'Unavailable'}</b></span>}{item.data?.score!=null&&<span>Signal score <b>{item.data.score}</b></span>}{item.data?.researchWindow&&<span>Research window <b>{item.data.researchWindow.from} – {item.data.researchWindow.to}</b></span>}{item.data?.conclusionConfidence&&<span>Evidence <b>{label(item.data.conclusionConfidence)}</b></span>}{item.data?.topFindings?.map((finding)=><span key={finding.id}>Finding <b>{finding.title}</b></span>)}<span>Source <b>{item.source}</b></span><span>References <b>{item.references.map((reference)=>`${reference.type}:${reference.id}`).join(' · ')}</b></span></div></details>}</div>
  </article>}

export default function ResearchTimelineSection({caseItem}){
  const[data,setData]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState(false);const[filter,setFilter]=useState('ALL');
  useEffect(()=>{const controller=new AbortController();setLoading(true);setError(false);getResearchCaseTimeline(caseItem.id,controller.signal).then(setData).catch((reason)=>{if(reason.name!=='AbortError')setError(true)}).finally(()=>{if(!controller.signal.aborted)setLoading(false)});return()=>controller.abort()},[caseItem.id]);
  const events=useMemo(()=>data?.events?.filter((item)=>filter==='ALL'||CATEGORY_GROUP[item.category]===filter)||[],[data,filter]);const groups=useMemo(()=>events.reduce((map,item)=>{if(!map.has(item.effectiveDate))map.set(item.effectiveDate,[]);map.get(item.effectiveDate).push(item);return map},new Map()),[events]);
  return <section className="protocol-section protocol-timeline"><div className="timeline-title"><div><span className="analytics-module-kicker">Research timeline</span><h2>What happened after Zig noticed it?</h2><p>Original Case evidence remains immutable; follow-up uses later canonical and persisted research activity.</p></div>{data&&<div className="timeline-filters">{FILTERS.map((value)=><button type="button" key={value} className={filter===value?'is-active':''} onClick={()=>setFilter(value)}>{value}</button>)}</div>}</div>
    {loading&&<div className="signal-history-loading"><i/><i/><i/></div>}{error&&<div className="protocol-history-empty"><strong>Research Timeline is temporarily unavailable.</strong><span>Other dossier sections remain available.</span></div>}
    {!loading&&!error&&data&&<><div className="timeline-summary"><span>Created <b>{day(data.case.snapshotDate)}</b></span><span>Latest follow-up <b>{day(data.currentFollowUp.canonicalDate)}</b></span><span>Signal now <b>{label(data.currentFollowUp.signalState||'Unavailable')}</b></span><span>Lifecycle now <b>{label(data.currentFollowUp.lifecycleState||'Unavailable')}</b></span><span>Meaningful changes <b>{data.summary.meaningfulChanges}</b></span><span>Research / synthesis <b>{data.summary.researchEvents} / {data.summary.synthesisEvents}</b></span></div><p className="timeline-disclosure">{data.disclosure}</p>{data.sourceFailures?.length>0&&<p className="timeline-source-note">Some follow-up sources are temporarily unavailable; the remaining persisted timeline is shown.</p>}{groups.size===0?<div className="protocol-history-empty"><strong>No events match this filter.</strong></div>:<div className="research-timeline">{[...groups].map(([dateValue,items],index)=><section className="timeline-day" key={dateValue}><div className="timeline-date"><time dateTime={dateValue}>{day(dateValue)}</time>{index===0&&<span>Original case</span>}{index===1&&<span>Follow-up</span>}</div><div className="timeline-events">{items.map((item)=><TimelineEvent key={item.id} item={item}/>)}</div></section>)}</div>}</>}
  </section>;
}
